### PR TITLE
Wip/auto format

### PR DESCRIPTION
**Pull request by JonnyH**
Let's make our git history useless!

### CODE REVIEW

**Comment by LavenderMoon** [comment]
Heh, I nearly started complaining about the style changes until I saw a pointer and realized I was looking at OpenApoc instead of OpenRA.

**Comment by pmprog** [comment]
Is there any reason this hasn't been merged?

**Comment by JonnyH** [comment]
I'm still not 100% decided on a style, I was hoping you would have an opinion as to which of the updates to this branch you prefer.

Then I'll rebase the whole thing against current head and reformat and push.

**Comment by JonnyH** [comment]
(Realised I didn't push the other one to compare :)

Effectively do you prefer this, or https://github.com/JonnyH/OpenApoc/tree/WIP/auto-format2 ? I'm pretty much on the fence between the two, if you have any preference let me know and I'll rebase, reformat & push.

**Comment by pmprog** [comment]
Pull auto-format3 when you're ready :)

**Pull request closed without merging**
